### ISSUE TITLE
Heroku deployment is broken

### ISSUE THREAD

**Issue by bengravesdev** [nexmo-se/townhall#5]
Opening the demo once its deployed using Heroku results in a blank page with the following line in the browser console:

Uncaught SyntaxError: expected expression, got '<' volta.min.js:1

I tried deploying it twice. Once in the EU and again in the US.

**Comment by franziz** [comment]
Hi @mobilisedonline, the page will be blank if you are not pointing to correct URL. Please take a look at README.md for list of URLs.

**Comment by bengravesdev** [comment]
That was a quick reply. I was just about to close this myself when I realised. Thanks.
